### ISSUE TITLE
[bug?] calculated line-heights are not always whole-number multiples of the base line-height

### ISSUE THREAD

**Issue by mprast** [kyleshevlin/shevyjs#24] opened 2020-03-22 03:10 UTC
It appears in the code that shevy increments the multiple by a factor of 0.5 when calculating the line-height for a font:

https://github.com/kyleshevlin/shevyjs/blob/master/src/utils/index.js#L54

I might be missing something, but this seems at odds with your documentation:

https://github.com/kyleshevlin/shevyjs/blob/master/src/utils/index.js#L54

(in particular: _Each line height calculated will be a multiple or dividend of this value._)

Is Shevy working as intended here, or is this a bug? I've verified that it is indeed producing fractional multiples of the base line-height - my config is 

```typescript
  export const shevy = new Shevy({
    baseFontSize: "16px",
    baseLineHeight: 1.5,
    baseFontScale: "majorThird",
    addMarginBottom: true,
    proximity: false
  });
```
and my h3 font-size ends up being 31.248px with a line-height of 36px - 1.5x the base line-height of 24px. Thanks for your help!

**Comment by kyleshevlin** [comment] 2020-03-23 16:41
Yeah, this is working as intended, so perhaps the language should be updated in the docs. The idea with incrementing by `.5` to find an appropriate height is that using an integer can produce unreasonable line-heights. In your case, you'd end up with a line-height of 48px which would end up putting 9.5 px above and below your text before we even get to the margins.

Sorry that this was confusing. I'm going to close this issue. Happy to consider a PR for better docs language in this situation.

**Closed by kyleshevlin** 2020-03-23 16:41 UTC

**Comment by mprast** [comment] 2020-03-23 18:01
@kyleshevlin no worries; thanks for the speedy response! I'll take a stab at updating the docs
